Add new function to shellrc

diff --git a/shellrc b/shellrc
--- a/shellrc
+++ b/shellrc
@@ -49,6 +49,14 @@ alias tyc='typst compile'
 function tywin () {
   powershell.exe "typst w $*"
 }
+cn () {
+  lastline=$(find . -maxdepth 1 -a -type d | grep -xE '(./)?[0-9_]+/?' | tail -n 1)
+  if [ -n "$lastline" ]; then
+    cd "$lastline" || echo "Failed to enter \"$lastline\"" >&2
+  else
+    echo "There are not matched directory." >&2
+  fi
+}
 
 # aliases and function for mamba and conda
 function caf () {
